ARG JDK_VERSION=17
FROM eclipse-temurin:${JDK_VERSION}-jdk AS builder

# Set working directory
WORKDIR /app

# Install sbt
RUN \
    apt-get update && \
    apt-get install -y curl gnupg apt-transport-https && \
    echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | tee /etc/apt/sources.list.d/sbt.list && \
    echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee /etc/apt/sources.list.d/sbt_old.list && \
    curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/scalasbt-release.gpg --import && \
    chmod 644 /etc/apt/trusted.gpg.d/scalasbt-release.gpg && \
    apt-get update && \
    apt-get install -y sbt && \
    rm -rf /var/lib/apt/lists/*

# Copy build files first to leverage Docker caching
COPY build.sbt .
COPY project ./project

# Download dependencies
RUN sbt update

# Copy the rest of the application source code
COPY . .

# Build the application using sbt stage
RUN sbt clean stage

# Set the base image for the final stage
FROM eclipse-temurin:${JDK_VERSION}-jre AS runner

WORKDIR /app

# Copying the built application artifacts from the builder stage
COPY --from=builder /app/target/universal/stage .

# Exposing the port the application runs on (default Play port is 9000)
EXPOSE 9000

CMD ["sh", "-c", "rm -f /app/RUNNING_PID && ./bin/play-scala-seed"]