name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ebiznes-zadanie10/backend
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci || npm install
        
      - name: Build backend
        run: npm run build --if-present
        
      - name: Test backend
        run: npm test --if-present

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ebiznes-zadanie10/frontend
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci || npm install
        
      - name: Build frontend
        run: npm run build
        
      - name: Test frontend
        run: npm test --if-present -- --passWithNoTests